package games.absolutephoenix.atlasservermanager.managers;

/*
The MIT License (MIT)

Copyright (c) 2021 Absolute_Phoenix

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
persons to whom the Software is furnished to do so, subject to the following conditions:
1: All products using this code may not make revenue.
2: Any project using this project or significant portions of this project must give credit to the original copyright holder.
*/


import games.absolutephoenix.atlasservermanager.utils.HelperMethods;
import games.absolutephoenix.atlasservermanager.utils.frameworks.DiscordWebhookFramework;

import java.awt.*;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;

public class DiscordWebhookManager {
    public static void SendWebhook(String webhookURL, String username, String avatar, String title, String content, boolean thumnail, String x, String y, int port, String startMethod, Color color) throws IOException {
        DiscordWebhookFramework discordWebhook = new DiscordWebhookFramework(webhookURL);
        discordWebhook.setUsername(username);
        discordWebhook.setAvatarUrl(avatar);
        discordWebhook.addEmbed(Embed(title, content, thumnail, x, y, port, startMethod, color));
        try {
            discordWebhook.execute();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static DiscordWebhookFramework.EmbedObject Embed(String title, String content, boolean thumbnail, String x, String y,  int port, String startMethod, Color color) throws IOException {
        TimeZone tz = TimeZone.getTimeZone("UTC");
        DateFormat df = new SimpleDateFormat("yyy-MM-dd'T'HH:mm:ss.SSS'Z'"); // Quoted "Z" to indicate UTC, no timezone offset
        df.setTimeZone(tz);
        String time = df.format(new Date());

        DiscordWebhookFramework.EmbedObject embedObject = new DiscordWebhookFramework.EmbedObject();
        embedObject.setTitle(title);
        embedObject.setDescription(content);
        embedObject.setFooter("Generated by Complete Atlas Server Manager" , null);
        if (thumbnail)
            embedObject.setThumbnail("https://b.thumbs.redditmedia.com/8in3lDndYdhG6GA3w0GdbiUZAOd0KY2L9_xD1_e-D0M.png");
        embedObject.addField("X-Position", x, true);
        embedObject.addField("Y-Position", y, true);
        embedObject.addField("IP/Port", HelperMethods.getExternalIp() + ":" + port, true);
        embedObject.addField("Load Method", startMethod, false);
        embedObject.setColor(color);
        embedObject.setTimestamp(time);
        return embedObject;
    }
}
